<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Careers</name>
   <tag></tag>
   <elementGuidId>9ac17935-9959-4208-8d8c-a10c73e59faa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'Careers')])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.footer-main > ul > li:nth-of-type(5) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4d6996bd-d7fc-4b1c-974b-54d1a6bd7d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en/company/careers</value>
      <webElementGuid>3ee58c4c-33df-440f-b5c7-aa6fc9550d13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        Careers
    </value>
      <webElementGuid>c5aac062-942e-47cc-801f-a567571d3d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;FreeTrialPage&quot;]/footer[1]/section[@class=&quot;footer-top-main&quot;]/div[@class=&quot;footer-main-section&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6 col-md-6 col-lg-3&quot;]/div[@class=&quot;footer-main&quot;]/ul[1]/li[5]/a[1]</value>
      <webElementGuid>209fdcd8-bff0-4979-bce1-1a40fe7f2460</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Careers')])[3]</value>
      <webElementGuid>f73e57bf-93a8-44b7-9ec8-30f32cdda07d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='News Articles'])[3]/following::a[1]</value>
      <webElementGuid>8979a144-9fbd-4a61-9ba4-97bf7b389148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Press Releases'])[3]/following::a[2]</value>
      <webElementGuid>fedae276-9695-4f3b-904c-14ddb4180560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn More'])[1]/preceding::a[1]</value>
      <webElementGuid>b0c16631-9799-49d8-ad41-caf8eb10cbea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open Source HRMS'])[1]/preceding::a[1]</value>
      <webElementGuid>0ea1f4cf-8325-4af6-8ce0-5c739f347c05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/en/company/careers')])[3]</value>
      <webElementGuid>1ced5e18-446c-4db8-ae31-c3b883a98843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/ul/li[5]/a</value>
      <webElementGuid>270fe195-3eb1-47d4-9b2b-d0f1218479ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/en/company/careers' and (text() = '
        Careers
    ' or . = '
        Careers
    ')]</value>
      <webElementGuid>22fbde5d-faa7-4bcc-99d3-dfcf3acbf7f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
