<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_OrangeHRM</name>
   <tag></tag>
   <elementGuidId>be749006-4d73-4067-b673-738f72e2b3b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'OrangeHRM')])[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.footer-main > ul > li > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>49453854-2345-4f21-9460-d91a9b9fdd7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en/company/about-us</value>
      <webElementGuid>05540862-2553-4c17-a96f-d9c40459d651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>cdd40dc5-ee36-4397-9ea5-ab65cdc64a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener</value>
      <webElementGuid>38baff17-2de5-4e88-8c7d-f35fa1c85aa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        OrangeHRM
    </value>
      <webElementGuid>d3b1e044-55a6-48dd-b587-4606661fe9da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;FreeTrialPage&quot;]/footer[1]/section[@class=&quot;footer-top-main&quot;]/div[@class=&quot;footer-main-section&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6 col-md-6 col-lg-3&quot;]/div[@class=&quot;footer-main&quot;]/ul[1]/li[1]/a[1]</value>
      <webElementGuid>eb1c8a61-0d4d-41e3-8ca9-0155b5212cc3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'OrangeHRM')])[7]</value>
      <webElementGuid>9d296be1-f240-41c1-bd0b-fcd2c3ade2c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Us'])[3]/following::a[1]</value>
      <webElementGuid>9096bc20-1131-4e3f-86c1-4a67756d8ba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operating vacancies'])[1]/following::a[1]</value>
      <webElementGuid>a27eddf7-7623-4f18-b92c-e98abc9cb495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Executive Profile'])[1]/preceding::a[1]</value>
      <webElementGuid>21dd0135-3071-47b1-a6d0-830d460b5694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Press Releases'])[3]/preceding::a[2]</value>
      <webElementGuid>4094db2e-69e7-445a-b602-42b08d30b400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OrangeHRM']/parent::*</value>
      <webElementGuid>0deb589b-45e4-4f21-b2e2-01fb29d637ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/en/company/about-us')])[3]</value>
      <webElementGuid>1234e93d-5281-4217-b7f6-7e5fbdf2bb34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/ul/li/a</value>
      <webElementGuid>a6e0e55a-8912-425d-9612-81b6085cb445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/en/company/about-us' and (text() = '
        OrangeHRM
    ' or . = '
        OrangeHRM
    ')]</value>
      <webElementGuid>ff6c88f0-467d-40ca-9753-4772d94d0608</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
