<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Testimonials</name>
   <tag></tag>
   <elementGuidId>df97848f-8791-4b1c-9128-64c3bfaa173d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'Testimonials')])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d7b27613-1965-449b-afeb-8c329c5dfc7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/en/why-orangehrm/our-customers/testimonials</value>
      <webElementGuid>56d09bed-6394-43f5-83c1-7fd8620664f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>4cb79221-365b-4f4a-8f62-abf4bab09203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener</value>
      <webElementGuid>dd96f59e-4855-4e7f-a415-93f2c94076b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        Testimonials
    </value>
      <webElementGuid>c18d1b14-219c-40aa-beab-edb53026a47b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;FreeTrialPage&quot;]/footer[1]/section[@class=&quot;footer-top-main&quot;]/div[@class=&quot;footer-main-section&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6 col-md-6 col-lg-3&quot;]/div[@class=&quot;footer-main&quot;]/ul[1]/li[4]/a[1]</value>
      <webElementGuid>13a28e84-8821-48cc-83d8-ddafb67e5401</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Testimonials')])[3]</value>
      <webElementGuid>0f910dda-c69a-41cb-ab3b-bfcd2bdaf5e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our Partners'])[3]/following::a[1]</value>
      <webElementGuid>ed89a8a0-e1eb-4c14-b48d-a3044d7df37c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CS &amp; Support'])[3]/following::a[2]</value>
      <webElementGuid>f8b48891-957c-4e80-81e6-0512d9108c99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OrangeHRM API'])[3]/preceding::a[1]</value>
      <webElementGuid>22ab0d35-c401-4d59-9960-adb43c26788c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Policies'])[1]/preceding::a[2]</value>
      <webElementGuid>edacb35a-673c-418f-9be5-de2faec24e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/en/why-orangehrm/our-customers/testimonials')])[3]</value>
      <webElementGuid>317f7a63-a870-42ea-a4ba-d0504af55639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[4]/a</value>
      <webElementGuid>dbd82e06-4a9e-47d7-94e6-779bc589123c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/en/why-orangehrm/our-customers/testimonials' and (text() = '
        Testimonials
    ' or . = '
        Testimonials
    ')]</value>
      <webElementGuid>b58a2c0e-28fa-45a2-80c0-d05079e348d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
