<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Country_a-oujh39qlxlur</name>
   <tag></tag>
   <elementGuidId>b681fd22-0a14-4d5c-9194-13cd0932abd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-oujh39qlxlur']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-oujh39qlxlur&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>11c57900-9bff-4156-8e46-a7b94f9dd001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>371506c7-8b5c-4423-ad26-62b31adf411d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>0b90116c-4b6a-4c7c-9e7c-e1c4c0af22b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>90c35d1a-1359-4d1c-8902-55086fe7e1d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>75854bdd-6bf2-4396-94c0-198fe767dae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-oujh39qlxlur</value>
      <webElementGuid>affc483b-9ecd-4fcc-af64-d01ec00a662d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ce5e6e82-c5a5-4dc2-b59b-61c4661fd3b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>aa5421f0-523e-471c-b57f-cb5f79592901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>4edfc327-c0a9-466e-b5ef-bf01fd876c30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6Ld_-LcqAAAAAPbS9l-LgseMiB-svnHzxIiqfF5h&amp;co=aHR0cHM6Ly9vcmFuZ2Vocm0uY29tOjQ0Mw..&amp;hl=en&amp;type=image&amp;v=IyZ984yGrXrBd6ihLOYGwy9X&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;cb=rsjis71601o5</value>
      <webElementGuid>34788efb-7188-4fec-992a-cd1fac45268a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lf-yt-playback-inspected-xbp1oaewrnz7edvj</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7f0eab47-1a24-43f4-82fe-0e7e510b5fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lf-vimeo-playback-inspected-xbp1oaewrnz7edvj</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0f64b8eb-f05a-4e7e-85f7-da560c636516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Nocaptcha-Form_getForm_Captcha&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>7c85dcc7-5cec-462f-9ddd-2c7103ee4100</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-oujh39qlxlur']</value>
      <webElementGuid>ec384a37-7f1e-4a05-a8cb-88567b0ba0e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Nocaptcha-Form_getForm_Captcha']/div/div/iframe</value>
      <webElementGuid>391ae078-195e-4246-a580-f970c9195f05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/iframe</value>
      <webElementGuid>bb645570-ed7c-4144-a446-e55d260c3ae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-oujh39qlxlur' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6Ld_-LcqAAAAAPbS9l-LgseMiB-svnHzxIiqfF5h&amp;co=aHR0cHM6Ly9vcmFuZ2Vocm0uY29tOjQ0Mw..&amp;hl=en&amp;type=image&amp;v=IyZ984yGrXrBd6ihLOYGwy9X&amp;theme=light&amp;size=normal&amp;badge=bottomright&amp;cb=rsjis71601o5']</value>
      <webElementGuid>944221ae-f2fe-4bee-811d-0f0fe5207f5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
