<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Country_action_submitForm</name>
   <tag></tag>
   <elementGuidId>a0b8b16e-0e3f-47a1-96bb-623b4e2cc2db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Form_getForm_action_submitForm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Form_getForm_action_submitForm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>540a8112-1e70-4b8f-8453-89fd346424af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>59650d1b-a57f-4d89-bcda-9aba5555428a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>action_submitForm</value>
      <webElementGuid>c44f2fe3-a5aa-4e89-ad5d-62a5c41c227d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Obtén tu prueba gratuita</value>
      <webElementGuid>43094972-43eb-46ce-a6bc-52f415456fb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>action</value>
      <webElementGuid>7f0f2fe1-8f19-4724-ac11-c4fdcf051818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Form_getForm_action_submitForm</value>
      <webElementGuid>664ccbc6-fc1c-425c-845b-31f8c5547dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>0185ae28-9728-4b32-b7e9-0e06dc985ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Form_getForm_action_submitForm&quot;)</value>
      <webElementGuid>d55f0cd7-8f8a-431f-a164-cc42ec39d47f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Form_getForm_action_submitForm']</value>
      <webElementGuid>5bc4cb5a-976d-4d93-bca6-e5ed71a8eefd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='Form_getForm']/div/input</value>
      <webElementGuid>29144802-5c1e-4968-ab15-8738ae649f35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input</value>
      <webElementGuid>541e2a34-462b-4624-bad4-ce8c437c4aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'action_submitForm' and @id = 'Form_getForm_action_submitForm']</value>
      <webElementGuid>97ce4c45-dd1d-47ab-8f2f-a9157d78d28e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
