<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Administrator AccessYou have requested _723b17</name>
   <tag></tag>
   <elementGuidId>0f4481b4-3d9b-4ab9-aa66-9947dbc8b513</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.orangehrm-card-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>032935e1-4294-4f80-a2c2-aac843b94abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>orangehrm-card-container</value>
      <webElementGuid>18c07051-2925-4313-a832-e14afb61a37c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Administrator AccessYou have requested to access a critical Administrator function in OrangeHRM and are required to validate your credentials belowUsernamePassword Cancel  Confirm </value>
      <webElementGuid>b128847c-ab63-4419-ae42-ee8d55f138da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;orangehrm-admin-access-container&quot;]/div[@class=&quot;orangehrm-card-container&quot;]</value>
      <webElementGuid>a203d8ea-1550-4eb3-95db-a4d7812056d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div</value>
      <webElementGuid>338a51e6-2e6d-45c3-91a8-3820f6c1d7a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>9ee3676d-8fe9-425f-a7f8-fa949f0c5167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Administrator AccessYou have requested to access a critical Administrator function in OrangeHRM and are required to validate your credentials belowUsernamePassword Cancel  Confirm ' or . = 'Administrator AccessYou have requested to access a critical Administrator function in OrangeHRM and are required to validate your credentials belowUsernamePassword Cancel  Confirm ')]</value>
      <webElementGuid>4de55961-4cb3-46be-bb70-b83b753ca353</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
