<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Primary ColorHEXSecondary ColorPrimary _38a963</name>
   <tag></tag>
   <elementGuidId>a7b43fd1-98c8-481e-81bc-e3de156135ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div/div/form/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.oxd-grid-4.orangehrm-full-width-grid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>13725a72-1e47-446e-b437-877087cd18e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-grid-4 orangehrm-full-width-grid</value>
      <webElementGuid>0e31065a-9485-46fb-871d-d7b8c385c710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Primary ColorHEXSecondary ColorPrimary Font ColorSecondary Font ColorPrimary Gradient Color 1Primary Gradient Color 2</value>
      <webElementGuid>976b2197-cfa3-496b-956e-341b401cb272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout orangehrm-upgrade-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]/div[@class=&quot;orangehrm-background-container&quot;]/div[@class=&quot;orangehrm-card-container&quot;]/form[@class=&quot;oxd-form&quot;]/div[@class=&quot;oxd-form-row&quot;]/div[@class=&quot;oxd-grid-4 orangehrm-full-width-grid&quot;]</value>
      <webElementGuid>4f29c5d5-9560-4257-abfd-fa9d9d03d963</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div/form/div/div</value>
      <webElementGuid>6de31ed6-9cd9-4bf7-b51a-968c234ecb26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configuration'])[1]/following::div[8]</value>
      <webElementGuid>297dc7fa-9063-4e42-83c4-8eb6e303d06c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div</value>
      <webElementGuid>236cb1e1-2a7b-4fea-ba23-b80a7ca3f02b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Primary ColorHEXSecondary ColorPrimary Font ColorSecondary Font ColorPrimary Gradient Color 1Primary Gradient Color 2' or . = 'Primary ColorHEXSecondary ColorPrimary Font ColorSecondary Font ColorPrimary Gradient Color 1Primary Gradient Color 2')]</value>
      <webElementGuid>b50f46e5-29b0-44df-9b55-9359e4914f2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
