<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Employee NameInvalidReference IdEvent _91e88c</name>
   <tag></tag>
   <elementGuidId>2308eab6-189e-4ff7-9a50-8c49e5828912</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div/div[2]/form</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>form.oxd-form</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>c7c2915a-f145-4863-b91c-07aef941ffe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-form</value>
      <webElementGuid>96011ad5-be3e-4dcf-9af9-9a01dde13fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Employee NameInvalidReference IdEvent Name-- Select --Status-- Select --From DateTo DateIncludeCurrent Employees Only Reset  Search </value>
      <webElementGuid>d6d14892-7794-4938-a57b-0b362592fae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout orangehrm-upgrade-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]/div[@class=&quot;oxd-table-filter&quot;]/div[@class=&quot;oxd-table-filter-area&quot;]/form[@class=&quot;oxd-form&quot;]</value>
      <webElementGuid>9a1dfa96-fe11-4ce5-b7f8-be1e84828ed7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div[2]/form</value>
      <webElementGuid>529bb1d1-bbc0-4832-a7df-96a4645eb8cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configuration'])[1]/following::form[1]</value>
      <webElementGuid>88571173-d624-43e4-952c-ac772eb5fee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>a35a120d-82fa-474e-b255-90e5c9e727d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[(text() = 'Employee NameInvalidReference IdEvent Name-- Select --Status-- Select --From DateTo DateIncludeCurrent Employees Only Reset  Search ' or . = 'Employee NameInvalidReference IdEvent Name-- Select --Status-- Select --From DateTo DateIncludeCurrent Employees Only Reset  Search ')]</value>
      <webElementGuid>9e12cb66-f3df-4276-8d4e-e8c67b74a600</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
