<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_httpsgoo.glmapsSNFWU86BcFSTaZM69</name>
   <tag></tag>
   <elementGuidId>36dcaca9-f7d3-4bd2-b9ee-6ec962dabeb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'https://goo.gl/maps/SNFWU86BcFSTaZM69')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2398c550-cfaf-4659-8578-3b627a287500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://goo.gl/maps/SNFWU86BcFSTaZM69</value>
      <webElementGuid>158ac2d7-1c85-42df-8e1e-aa91328c8e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>https://goo.gl/maps/SNFWU86BcFSTaZM69</value>
      <webElementGuid>f3c789c8-8463-4576-8907-87984d9acd0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;OurOffices&quot;]/div[@class=&quot;main&quot;]/div[@class=&quot;inner typography line&quot;]/div[@class=&quot;our-office-main&quot;]/section[@class=&quot;office-location-section&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-4 col-md-6 col-sm-4&quot;]/div[@class=&quot;office-location-menu&quot;]/div[@class=&quot;office-details&quot;]/div[@class=&quot;office-location-map&quot;]/a[1]</value>
      <webElementGuid>80eef9d7-4768-4bec-a193-1bfe9a62130a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'https://goo.gl/maps/SNFWU86BcFSTaZM69')]</value>
      <webElementGuid>8a44ea37-212f-4b99-90f8-dbf985dcaa6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://goo.gl/maps/6iHsd6dfjAuL3uQH8'])[1]/following::a[2]</value>
      <webElementGuid>0e90c285-ab5f-4e73-917b-e97f176d6a6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our Offices'])[1]/following::a[3]</value>
      <webElementGuid>4e4ee651-bbc2-4edb-aa80-1e8e4c51d238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://goo.gl/maps/KFPvNXwL8Kf1SsyT6'])[1]/preceding::a[3]</value>
      <webElementGuid>cc2c6211-9ca6-482e-88f0-75c7086d60f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://goo.gl/maps/rfWKvsgFhLuwwCcQ7'])[1]/preceding::a[5]</value>
      <webElementGuid>69ae167e-d099-4615-bdcb-3e73774364c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='https://goo.gl/maps/SNFWU86BcFSTaZM69']/parent::*</value>
      <webElementGuid>d0556bd3-8a59-4553-94b1-71893a5a7e86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://goo.gl/maps/SNFWU86BcFSTaZM69')]</value>
      <webElementGuid>78c07b21-f48b-4e2d-b15e-2bc85ac404ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]/a</value>
      <webElementGuid>62b04b45-dd7b-4fcd-b95e-000e3616b2dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://goo.gl/maps/SNFWU86BcFSTaZM69' and (text() = 'https://goo.gl/maps/SNFWU86BcFSTaZM69' or . = 'https://goo.gl/maps/SNFWU86BcFSTaZM69')]</value>
      <webElementGuid>df0ca546-e291-4302-a35b-3739b7917545</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
