<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>d009be90-f953-4265-aca7-f7d9826f769b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Sandals']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Sandals&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3e950af4-da8c-4422-9675-eb5e57836560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/Uploads/Advanced-client-logo-/2.webp</value>
      <webElementGuid>f1429a06-d4ba-401f-b27f-6c44159938c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>/assets/Uploads/Advanced-client-logo-/2.webp</value>
      <webElementGuid>4dd91de1-6424-462d-b43c-a1db0f31725a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Sandals</value>
      <webElementGuid>e3a2cafb-9ff7-4f7e-8c8c-872a38a7d898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;HomePage no-sidebar&quot;]/div[@class=&quot;main&quot;]/div[@class=&quot;inner typography line&quot;]/div[@class=&quot;fixed-nav-padding home&quot;]/section[@class=&quot;homepage-activeuser-section&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row homepage-activeuser&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;homepage-clients-logo&quot;]/div[@class=&quot;container text-center my-3&quot;]/div[@class=&quot;row mx-auto my-auto justify-content-center&quot;]/div[@class=&quot;owl-carousel owl-loaded owl-drag&quot;]/div[@class=&quot;owl-stage-outer&quot;]/div[@class=&quot;owl-stage&quot;]/div[@class=&quot;owl-item&quot;]/div[@class=&quot;item&quot;]/div[@class=&quot;card-img starter-activeuser-sub&quot;]/img[1]</value>
      <webElementGuid>d2c789c2-f287-4b5d-9205-82ab6c30dcd3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Sandals']</value>
      <webElementGuid>caa61835-9eda-4913-9d00-f92fc5905ea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/img</value>
      <webElementGuid>413a9358-8227-42ce-8225-768a613c0258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/Uploads/Advanced-client-logo-/2.webp' and @alt = 'Sandals']</value>
      <webElementGuid>9472b1da-2d91-436b-aebd-08d4198ffbb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
