<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_EmailHomePage</name>
   <tag></tag>
   <elementGuidId>d4fd3ca4-a2a4-46f9-bd23-0dcbf15c9caf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Form_submitForm_EmailHomePage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Form_submitForm_EmailHomePage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9759a481-4811-4cbd-b7b6-0383efae0093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>bb415f53-2a12-4d54-bd53-8b677e84d480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EmailHomePage</value>
      <webElementGuid>49e9d091-457e-45e1-9d9f-311fdc31ce8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>email text tryit-email</value>
      <webElementGuid>c0451ce0-e214-4cc3-bfe6-72b8bd4ee514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Form_submitForm_EmailHomePage</value>
      <webElementGuid>f309113c-4df5-4300-b6f8-04f43ae4006a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9f4c1b3f-2cac-4b0a-8c2c-38cf7e3c50ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your email address here</value>
      <webElementGuid>1def556e-c541-4a8e-ac80-0f5e974ecd30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Form_submitForm_EmailHomePage&quot;)</value>
      <webElementGuid>af03da7e-fb98-42a3-a43e-a94be6c3931b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Form_submitForm_EmailHomePage']</value>
      <webElementGuid>befeed4b-e6fd-4221-83f2-cb4ab0b6a92c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Form_submitForm_EmailHomePage_Holder']/div/input</value>
      <webElementGuid>989bf739-69bd-4919-aa56-8a6dbd1e4130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3ea46b3c-d1f4-48d2-a094-00dc3def410e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'EmailHomePage' and @id = 'Form_submitForm_EmailHomePage' and @placeholder = 'Enter your email address here']</value>
      <webElementGuid>d29a1a7b-f8fe-44ab-8dc0-30410e5a0887</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
